### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by john-cullen** [GregsStack/InputSimulatorStandard#1]
Hello @Gh0stWalk3r 

The repository you forked from had forked an unlicensed repository and added a licence itself. However now the source repository has become MIT licence. 

It would be good if you could re-licence this repository to MIT.

Regards
John Cullen

**Comment by Gh0stWalk3r** [comment]
Hey @john-cullen 
Yes, I will update the license as soon as possible.
Thanks for reaching out to me for the license update, otherwise I would have missed the change or recognized it a lot later.

Have a great day,
Greg

**Comment by john-cullen** [comment]
Thanks for getting this sorted so quickly! :)
