### ISSUE TITLE
Please update nuget.org

### ISSUE THREAD

**Issue by SommerEngineering** [GregsStack/InputSimulatorStandard#14]
The latest version on nuget.org is v1.0.0. Github shows version 1.1.1. Can we please get these updates?

**Comment by Gh0stWalk3r** [comment]
Hi @SommerEngineering,
the package you are referring to has been uploaded by someone else who forked my repository and is therefore out of my reach to maintain. If you want to have the latest updates, please use https://www.nuget.org/packages/GregsStack.InputSimulatorStandard/

**Comment by Gh0stWalk3r** [comment]
I will close the issue for now. Feel free to re-open it when needed.

**Comment by SommerEngineering** [comment]
@Gh0stWalk3r, thank you for your quick reaction and your explanation. I will then switch to your package.
