### ISSUE TITLE
NUM_ENTER not supported

### ISSUE THREAD

**Issue by jkhoel** [GregsStack/InputSimulatorStandard#27]
As the title says - Numpad Enter Key seems to be missing

**Comment by Gh0stWalk3r** [comment]
I will add it as soon as possible 🙂

**Comment by Gh0stWalk3r** [comment]
@jkhoel A new beta package is published soon, can you verify that it works for you?
Added new VirtualKeyCode NUMPAD_RETURN for ENTER key of numeric keyboard.

**Comment by jkhoel** [comment]
Excellent! I will do a test this coming weekend. Thank you very much :)

**Comment by jkhoel** [comment]
Hi! It took me a while to get around to testing this. But I just did, and it seems to work like a charm :)

**Comment by Gh0stWalk3r** [comment]
Good :)
I will create a new stable release package.
