### ISSUE TITLE
plz. Support dotnet 4.0 With standard 2.0

### ISSUE THREAD

**Issue by BBUBBA** [GregsStack/InputSimulatorStandard#91]
I tried Test Build...

1. Project File
       before                      `<TargetFramework>netstandard2.0</TargetFramework>`
       After                         `<TargetFrameworks>netstandard2.0;net40</TargetFrameworks>`

2. InputBuilder.cs
       before                      `private static readonly IReadOnlyList<VirtualKeyCode> ExtendedKeys = new List<VirtualKeyCode> ` 
       After                         `private static readonly List<VirtualKeyCode> ExtendedKeys = new List<VirtualKeyCode>`

Good Work..... Thank you..

**Comment by Gh0stWalk3r** [comment]
Hi @BBUBBA,
Thanks for your interest.
I will try to include .NET 4.0 support. I hope to complete it today 🙂

Greetings, Greg
