### ISSUE TITLE
Numpad_return and return both act as Numpad_return

### ISSUE THREAD

**Issue by silverlore** [GregsStack/InputSimulatorStandard#95]
I use the simulator for input to a game. And it does not matter if I send key stroke Numpad_return or return the game always pick up numpad_return. I think it is because the enum values are the same for both.

**Comment by Gh0stWalk3r** [comment]
That's true, both values are identical. I will have a look how to improve this so that it works as expected.

**Comment by Gh0stWalk3r** [comment]
Thank you very much for your help!
Your change has been merged and is already built. It should be available on NuGet in a couple of minutes.
